LINE_CHART = "line-chart"
stocks = ['AAPL', 
          'MSFT', 
          'GOOG', 
          'AMZN', 
          'NVDA', 
          'TSLA', 
          'BRK-B', 
          'META', 
          'TSM', 
          'V', 
          'MC.PA', 
          'UNH', 
          'JPM', 
          'JNJ', 
          'LLY', 
          'WMT', 
          'XOM', 
          'TCEHY', 
          'MA']